
<% uri = ENV['MONGOHQ_URL'] %>
<% database = uri ? uri.split('@')[1].split('/')[1] : '' %>
<% hosts = uri ?  uri.split('@')[1].split('/')[0].split(',')  : ''%>
<% user = uri ?  uri.split('@')[0].split(':')[0] : '' %>
<% password = uri ? uri.split('@')[0].split(':')[1] : ''%>

development:
   clients:
         default:
           database: <%= database.to_s %>
           hosts:
             - <%= hosts[0] %>
             - <%= hosts[1] %>
             - <%= hosts[2] %>
           options:
             user:  <%= user.to_s %>
             password:  <%= password.to_s %>
             auth_source: admin
             identity_map_enabled: true
             ssl: true
test:
   clients:
      default:
        database: <%= database.to_s %>
        hosts:
          - <%= hosts[0] %>
          - <%= hosts[1] %>
          - <%= hosts[2] %>
        options:
          user:  <%= user.to_s %>
          password:  <%= password.to_s %>
          auth_source: admin
          identity_map_enabled: true
          ssl: true
production:
  clients:
      default:
        database: <%= database.to_s %>
        hosts:
          - <%= hosts[0] %>
          - <%= hosts[1] %>
          - <%= hosts[2] %>
        options:
          user:  <%= user.to_s %>
          password:  <%= password.to_s %>
          auth_source: admin
          identity_map_enabled: true
          ssl: true